### ISSUE TITLE
Add new serializer - kotlin.serialization JSON

### ISSUE THREAD

**Issue by faogustavo** [faogustavo/kached#3]

**Comment by enzo-beltrami** [comment]
I'm working on this

**Comment by enzo-beltrami** [comment]
Just hit a wall while implementing this

`Json.encodeToString` method uses a reified T so I can only call it inside an inline function or forcing the class via `Json.encodeToString<kclass.java>`, however using `kclass.java` would limit the runtime to the jvm

**Comment by faogustavo** [comment]
@enzo-beltrami maybe we can have just a JVM version for now and then find a better way to do this.
